// ============================================================================
// Alaii ReelFarm — Reddit Engagement Engine
// ============================================================================
// Searches beauty subreddits for relevant posts and auto-comments
// with helpful, non-salesy replies generated by Claude.
// Targets: r/Esthetics, r/HairStylist, r/NailTech, r/MedSpa, etc.

import Anthropic from '@anthropic-ai/sdk';
import cron from 'node-cron';
import * as fs from 'fs';
import * as path from 'path';

// ============================================================================
// Reddit API Client (OAuth2 Script App)
// ============================================================================

const REDDIT_API = 'https://oauth.reddit.com';
let accessToken: string | null = null;
let tokenExpiry = 0;

function getRedditConfig() {
  const clientId = process.env.REDDIT_CLIENT_ID;
  const refreshToken = process.env.REDDIT_REFRESH_TOKEN;

  if (!clientId || !refreshToken) {
    throw new Error('Missing Reddit credentials (REDDIT_CLIENT_ID, REDDIT_REFRESH_TOKEN)');
  }

  return { clientId, refreshToken };
}

async function getAccessToken(): Promise<string> {
  if (accessToken && Date.now() < tokenExpiry) return accessToken;

  const config = getRedditConfig();
  // Devvit apps use client_id only auth (no secret needed for installed apps)
  const auth = Buffer.from(`${config.clientId}:`).toString('base64');

  const res = await fetch('https://www.reddit.com/api/v1/access_token', {
    method: 'POST',
    headers: {
      Authorization: `Basic ${auth}`,
      'Content-Type': 'application/x-www-form-urlencoded',
      'User-Agent': 'AlaiiBitby/1.0',
    },
    body: new URLSearchParams({
      grant_type: 'refresh_token',
      refresh_token: config.refreshToken,
    }),
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Reddit auth failed: ${err}`);
  }

  const data = await res.json();
  accessToken = data.access_token;
  tokenExpiry = Date.now() + (data.expires_in - 60) * 1000;
  console.log('🔑 Reddit access token refreshed');
  return accessToken!;
}

async function redditGet(endpoint: string): Promise<any> {
  const token = await getAccessToken();
  const res = await fetch(`${REDDIT_API}${endpoint}`, {
    headers: {
      Authorization: `Bearer ${token}`,
      'User-Agent': 'AlaiiBitby/1.0',
    },
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Reddit GET ${endpoint} failed: ${err}`);
  }

  return res.json();
}

async function redditPost(endpoint: string, body: Record<string, string>): Promise<any> {
  const token = await getAccessToken();
  const res = await fetch(`${REDDIT_API}${endpoint}`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/x-www-form-urlencoded',
      'User-Agent': 'AlaiiBitby/1.0',
    },
    body: new URLSearchParams(body),
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Reddit POST ${endpoint} failed: ${err}`);
  }

  return res.json();
}

// ============================================================================
// Beauty Subreddits & Search Queries
// ============================================================================

const BEAUTY_SUBREDDITS = [
  'Esthetics',
  'HairStylist',
  'NailTech',
  'MedSpa',
  'Lashes',
  'cosmetology',
  'BeautyIndustry',
  'SalonOwners',
  'Aesthetician',
  'microblading',
  'waxing',
  'barbershop',
];

const SEARCH_QUERIES = [
  'no shows booking',
  'scheduling software',
  'cancellation policy',
  'booking app recommendation',
  'client management',
  'growing my business',
  'filling empty slots',
  'marketing for salon',
  'getting more clients',
  'starting my own salon',
  'glossgenius vs',
  'square appointments',
  'best booking system',
];

// ============================================================================
// AI Comment Generation
// ============================================================================

async function generateRedditComment(post: any): Promise<string> {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) throw new Error('ANTHROPIC_API_KEY not set');

  const client = new Anthropic({ apiKey });

  const response = await client.messages.create({
    model: 'claude-sonnet-4-20250514',
    max_tokens: 250,
    messages: [{
      role: 'user',
      content: `Write a helpful Reddit comment on this beauty industry post. Rules:
1. Be genuinely helpful — give real actionable advice
2. Sound like a knowledgeable redditor, not a brand
3. ONLY mention Alaii if the post is specifically asking about booking/scheduling software — and even then say "I've been using something called Alaii" casually, not as a pitch
4. If the post is NOT about booking software, just give good advice with zero product mentions
5. Keep it under 150 words
6. Match the subreddit's tone — casual, supportive, community-like
7. Never use emojis excessively
8. Start with something empathetic or relatable

SUBREDDIT: r/${post.subreddit}
POST TITLE: ${post.title}
POST BODY: ${(post.body || '').slice(0, 500)}
UPVOTES: ${post.score}

Write ONLY the comment text.`,
    }],
  });

  const text = response.content[0];
  return text.type === 'text' ? text.text : '';
}

// ============================================================================
// Engagement Data
// ============================================================================

const REDDIT_LOG = path.join(process.cwd(), 'data', 'reddit-engagement.json');

interface RedditEngagement {
  postId: string;
  subreddit: string;
  postTitle: string;
  comment: string;
  action: 'comment' | 'upvote';
  timestamp: string;
}

function getRedditLog(): RedditEngagement[] {
  if (!fs.existsSync(REDDIT_LOG)) return [];
  return JSON.parse(fs.readFileSync(REDDIT_LOG, 'utf-8'));
}

function logRedditAction(record: RedditEngagement): void {
  const dir = path.join(process.cwd(), 'data');
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  const log = getRedditLog();
  log.push(record);
  fs.writeFileSync(REDDIT_LOG, JSON.stringify(log, null, 2));
}

function hasCommented(postId: string): boolean {
  return getRedditLog().some(r => r.postId === postId);
}

// ============================================================================
// Main Engagement Engine
// ============================================================================

const MAX_COMMENTS_PER_RUN = 10;
let isEngaging = false;

export async function runRedditEngagement(): Promise<{
  comments: number;
  subreddits: string[];
}> {
  if (isEngaging) {
    console.log('⏸️ Reddit engagement already running');
    return { comments: 0, subreddits: [] };
  }

  isEngaging = true;
  let comments = 0;
  const touchedSubs: string[] = [];

  try {
    console.log('\n📱 ══════════════════════════════════════════');
    console.log('   Reddit Engagement Engine Starting...');
    console.log('   ══════════════════════════════════════════\n');

    // Pick 3 random subreddits + 2 search queries
    const shuffledSubs = [...BEAUTY_SUBREDDITS].sort(() => Math.random() - 0.5);
    const subsToCheck = shuffledSubs.slice(0, 3);

    const shuffledQueries = [...SEARCH_QUERIES].sort(() => Math.random() - 0.5);
    const query = shuffledQueries[0];

    // METHOD 1: Browse hot posts in beauty subreddits
    for (const sub of subsToCheck) {
      if (comments >= MAX_COMMENTS_PER_RUN) break;
      touchedSubs.push(sub);

      try {
        console.log(`  📱 Checking r/${sub}...`);
        const data = await redditGet(`/r/${sub}/hot?limit=10`);
        const posts = (data.data?.children || []).map((c: any) => ({
          id: c.data.name,
          title: c.data.title,
          body: c.data.selftext,
          subreddit: sub,
          score: c.data.score,
          numComments: c.data.num_comments,
          url: c.data.permalink,
        }));

        for (const post of posts) {
          if (comments >= MAX_COMMENTS_PER_RUN) break;
          if (hasCommented(post.id)) continue;
          // Skip posts with too many comments (our comment would get buried)
          if (post.numComments > 50) continue;
          // Skip low-quality posts
          if (post.score < 2) continue;

          try {
            const comment = await generateRedditComment(post);
            if (!comment || comment.length < 20) continue;

            // Post the comment
            await redditPost('/api/comment', {
              thing_id: post.id,
              text: comment,
            });

            comments++;
            logRedditAction({
              postId: post.id,
              subreddit: sub,
              postTitle: post.title,
              comment,
              action: 'comment',
              timestamp: new Date().toISOString(),
            });

            console.log(`  💬 Commented on r/${sub}: "${post.title.slice(0, 60)}..."`);

            // Rate limit: 10 second gap
            await new Promise(r => setTimeout(r, 10000));
          } catch (err) {
            console.error(`  ❌ Comment error:`, err);
          }
        }
      } catch (err) {
        console.error(`  ❌ Error in r/${sub}:`, err);
      }
    }

    // METHOD 2: Search across all of Reddit for beauty booking questions
    if (comments < MAX_COMMENTS_PER_RUN) {
      try {
        console.log(`  🔍 Searching Reddit for: "${query}"`);
        const data = await redditGet(`/search?q=${encodeURIComponent(query)}&sort=new&limit=5&t=day`);
        const posts = (data.data?.children || []).map((c: any) => ({
          id: c.data.name,
          title: c.data.title,
          body: c.data.selftext,
          subreddit: c.data.subreddit,
          score: c.data.score,
          numComments: c.data.num_comments,
        }));

        for (const post of posts) {
          if (comments >= MAX_COMMENTS_PER_RUN) break;
          if (hasCommented(post.id)) continue;

          try {
            const comment = await generateRedditComment(post);
            if (!comment || comment.length < 20) continue;

            await redditPost('/api/comment', {
              thing_id: post.id,
              text: comment,
            });

            comments++;
            logRedditAction({
              postId: post.id,
              subreddit: post.subreddit,
              postTitle: post.title,
              comment,
              action: 'comment',
              timestamp: new Date().toISOString(),
            });

            console.log(`  💬 Commented on r/${post.subreddit}: "${post.title.slice(0, 60)}..."`);
            await new Promise(r => setTimeout(r, 10000));
          } catch (err) {
            console.error(`  ❌ Search comment error:`, err);
          }
        }
      } catch (err) {
        console.error(`  ❌ Search error:`, err);
      }
    }

    console.log('\n📱 ══════════════════════════════════════════');
    console.log(`   Reddit done: ${comments} comments across ${touchedSubs.join(', ')}`);
    console.log(`   Total logged: ${getRedditLog().length} actions`);
    console.log('   ══════════════════════════════════════════\n');

  } catch (error) {
    console.error('❌ Reddit engagement error:', error);
  } finally {
    isEngaging = false;
  }

  return { comments, subreddits: touchedSubs };
}

// ============================================================================
// Scheduler — Every 3 hours
// ============================================================================

export function startRedditEngagement(): void {
  console.log('📱 Reddit Engagement Engine initialized');
  console.log(`   📊 ${getRedditLog().length} total actions logged`);

  // Run every 3 hours
  cron.schedule('0 */3 * * *', async () => {
    console.log('⏰ Reddit engagement cycle triggered');
    const result = await runRedditEngagement();
    console.log(`📊 Reddit: ${result.comments} comments on ${result.subreddits.join(', ')}`);
  });

  console.log('   ⏰ Scheduled: every 3 hours\n');
}

// ============================================================================
// Stats
// ============================================================================

export function getRedditStats() {
  const log = getRedditLog();
  const today = new Date().toDateString();
  return {
    totalActions: log.length,
    today: log.filter(r => new Date(r.timestamp).toDateString() === today).length,
    bySubreddit: BEAUTY_SUBREDDITS.reduce((acc, sub) => {
      acc[sub] = log.filter(r => r.subreddit === sub).length;
      return acc;
    }, {} as Record<string, number>),
  };
}
